
[colors.bright]
black = "#222222"
blue = "#0000FF"
cyan = "#00FFFF"
green = "#00FF00"
magenta = "#FF00FF"
red = "#FF0000"
white = "#FFFFFF"
yellow = "#FFFF00"

[colors.normal]
black = "#000000"
blue = "#0000CC"
cyan = "#00CCCC"
green = "#00CC00"
magenta = "#CC00CC"
red = "#CC0000"
white = "#CCCCCC"
yellow = "#CCCC00"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 11

[font.normal]
family = "Cousine"

[window]
opacity = 0.9

[general]
live_config_reload = true
