
syntax on

set scrolloff=16

" linenums
set number
set numberwidth=4
set relativenumber

" search
set ignorecase
set smartcase
set incsearch

" annoying
set noswapfile
set nobackup
set noerrorbells
set belloff=all
set timeout timeoutlen=3000 ttimeoutlen=50

" tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4

" aliases in :!
let $BASH_ENV="/home/lutfisk/.bashrc"

" trailing indent
highlight ExtraWhitespace ctermfg=red cterm=underline
match ExtraWhitespace /\s\+$/

" 80 col marker
" set colorcolumn=80
" highlight ColorColumn ctermbg=none ctermfg=lightgreen cterm=underline

" colors
highlight Statement ctermfg=yellow
highlight PreProc ctermfg=lightblue
highlight Comment ctermfg=lightgreen

" ctrlp
set runtimepath^=~/.vim/ctrlp.vim
let g:ctrlp_map='<c-k>'
let g:ctrlp_custom_ignore='bin\|\.git\|\.o$\|\.a$\|\.so$\|\.bin$\|\.d$\|\.deps$\|\.hi$'
let g:ctrlp_working_path_mode=''

