
syntax on

set noerrorbells
set belloff=all

set number
set numberwidth=4
set relativenumber

set ignorecase
set smartcase

set noswapfile
set nobackup

set scrolloff=16

set incsearch

set tabstop=4
set softtabstop=4
set shiftwidth=4

let $BASH_ENV="/home/lutfisk/.bashrc"

