
alias mkd='mkdir'
alias dl='rm -rf'
alias mkf='touch'
alias mk='make'
alias cmk='cmake .'
alias pac='sudo pacman -S'
alias pacs='sudo pacman -Ss'
# alias pacu='sudo pacman -Syy && yay -Syy'
alias pacu='sudo pacman -Syyu && yay -Syyu'
alias cls='clear'
alias zip='zip -r'
alias pacr='sudo pacman -Rs'
alias yayr='yay -Rs' 
alias xbx='xboxdrv -D --detach-kernel-driver --silent --dbus disabled'
