#!/bin/bash

# ----- filesystem
alias ..="cd ../"
alias ls="lls -c"
alias mkd="mkdir"
alias mkf="touch"

# ----- git
alias gadd="git add"
alias gmv="git mv"
alias grm="git rm"
alias gcom="git commit"
alias gdiff="git diff"
alias gpush="git push origin"
alias gpull="git pull origin"
alias gstat="git status"
alias gclone="git clone --recursive"
alias glog="git log"
alias gamnd="git commit --amend"
alias grst="git reset"

# ----- make
alias mk="make"
alias mkc="make clean"
alias mkr="make run"
alias mki="sudo -E make install"

# ----- libvirt
alias virsh="virsh -c qemu:///system"
alias virt-viewer="virt-viewer -c qemu:///system"

# ----- firewall
alias fw="sudo ufw"
alias fwstat="sudo ufw status numbered"

host () {
	cut -d ' ' -f 1 <<< $(getent hosts $1)
}

# ----- custom
alias cloc="lcloc -c"
alias lmodorg="lmodorg -c"
alias lpass="sudo -E lpass"

# ----- misc
alias cls="clear"
alias zip="zip -r"

if [ "$LED" == "1" ]; then
	PS1='\[\e[93mled\e[0m >\] \[\e[92m\]\u\[\e[0m\]@\h \[\e[32m\]\w\[\e[0m\]> '
	return
fi

[[ $- != *i* ]] && return
PS1='\[\e[92m\]\u\[\e[0m\]@\h \[\e[32m\]\w\[\e[0m\]> '

neofetch
