#!/bin/bash

[[ $- != *i* ]] && return
PS1='\[\e[92m\]\u\[\e[0m\]@\h \[\e[32m\]\w\[\e[0m\]> '

alias ls="ls --color=always"

alias mkd="mkdir"
alias mkf="touch"
alias mk="make"

alias gadd="git add"
alias gmv="git mv"
alias grm="git rm"
alias gcom="git commit"
alias gdiff="git diff"
alias gpush="git push origin"
alias gpull="git pull origin"
alias gstat="git status"
alias gclone="git clone --recursive"
alias glog="git log"
alias gamnd="git commit --amend"
alias grst="git reset"

alias cls="clear"
alias zip="zip -r"

alias cloc="lcloc -c"
alias lmodorg="lmodorg -c"
alias lpass="sudo -E lpass"

alias ..="cd ../"

neofetch
