#!/bin/bash

# ----- filesystem
alias ..="cd ../"
alias ls="lls -c"
alias mkd="mkdir"
alias mkf="touch"

# ----- git
alias gadd="git add"
alias gmv="git mv"
alias grm="git rm"
alias gcom="git commit -S"
alias gdiff="git diff"
alias gpush="git push origin"
alias gpull="git pull --rebase origin"
alias gstat="git status"
alias gclone="git clone --recursive"
alias glog="git log --format='%x1B[33m%h.. %x1B[0m %x1B[92m%<(20)%an%x1B[0m %s%x1B[31m%d%x1B[0m'"
alias gamend="git commit --amend"
alias gcheck="git checkout"
alias grest="git restore"
alias gremote="git remote"
alias gconf="git config --global"
alias gco="git checkout"
alias gbranch="git branch"

# ----- make
alias mk="make"
alias mkc="make clean"
alias mkr="make run"
alias mki="sudo -E make install"

# ----- libvirt
alias virsh="virsh -c qemu:///system"
alias virt-viewer="virt-viewer -c qemu:///system"

# ----- firewall
alias fw="sudo ufw"
alias fwstat="sudo ufw status numbered"

host () {
	cut -d ' ' -f 1 <<< $(getent hosts $1)
}

# ----- custom
alias cloc="lcloc -c"
alias lmodorg="lmodorg -c"
alias lpass="sudo -E lpass"

export GPG_TTY="$(tty)"

if [ "$LED" == "1" ]; then
	PS1='\[\e[93mled\e[0m >\] \[\e[92m\]\u\[\e[0m\]@\h \[\e[32m\]\w\[\e[0m\]> '
	return
fi

if [ ! -z "$VIM" ]; then
	shopt -s expand_aliases
fi

[[ $- != *i* ]] && return
PS1='\[\e[92m\]\u\[\e[0m\]@\h \[\e[32m\]\w\[\e[0m\]> '

